## User specifc information

### Mandator information
OPENAI_API_KEY: openai api key here
DISCORD_BOT_TOKEN: your bot token here

## AI specifi settings

### Mandator information
INVETORY_PATH: inventory